version: '3.8'
services:

  db:
    image: postgres:12
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - $MYDB_LOCAL_PORT:$MYDB_DOCKER_PORT
    expose: 
      - 3306  
    logging:
      driver: none

  api:
    depends_on:
      - db
    links: 
      - db 
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=db
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
    - .:/myapp
    command: sh -c "npm install && npm run start"


  front:
      build:
        context: https://github.com/FasterDelivery/front.git
      ports:
        - 3000:3000


      