import Package from "../models/Package";
import { IPackage } from "../interfaces/IPackage";

const packageData: any = [
  {
    clientname: "Sidney Rothon",
    image: "http://dummyimage.com/181x100.png/dddddd/000000",
    quantity: 1,
    weight: 3.14,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "en curso",
    userId: 8,
  },
  {
    clientname: "Lianne Debney",
    image: "http://dummyimage.com/123x100.png/5fa2dd/ffffff",
    quantity: 4,
    weight: 9.34,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "en curso",
    userId: 10,
  },
  {
    clientname: "Pauline Guarin",
    image: "http://dummyimage.com/142x100.png/dddddd/000000",
    quantity: 2,
    weight: 6.07,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "en curso",
    userId: 5,
  },
  {
    clientname: "Emanuel Lockwood",
    image: "http://dummyimage.com/169x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 9.49,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 13,
  },
  {
    clientname: "Kimmie Hurkett",
    image: "http://dummyimage.com/118x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 9.73,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 9,
  },
  {
    clientname: "Moe Sawyer",
    image: "http://dummyimage.com/178x100.png/ff4444/ffffff",
    quantity: 5,
    weight: 3.89,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 19,
  },
  {
    clientname: "Leigh Bartolomivis",
    image: "http://dummyimage.com/212x100.png/cc0000/ffffff",
    quantity: 2,
    weight: 9.22,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "entregado",
    userId: 5,
  },
  {
    clientname: "Zena MacGorrie",
    image: "http://dummyimage.com/148x100.png/dddddd/000000",
    quantity: 4,
    weight: 4.14,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "entregado",
    userId: 6,
  },
  {
    clientname: "Page Rowlin",
    image: "http://dummyimage.com/168x100.png/cc0000/ffffff",
    quantity: 2,
    weight: 2.94,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "pendiente",
    userId: 10,
  },
  {
    clientname: "Carissa Duffrie",
    image: "http://dummyimage.com/186x100.png/dddddd/000000",
    quantity: 4,
    weight: 8.84,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 18,
  },
  {
    clientname: "Zorana Gohier",
    image: "http://dummyimage.com/246x100.png/dddddd/000000",
    quantity: 5,
    weight: 2.46,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "entregado",
    userId: 17,
  },
  {
    clientname: "Hyacinthia Fridd",
    image: "http://dummyimage.com/115x100.png/dddddd/000000",
    quantity: 2,
    weight: 9.78,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "pendiente",
    userId: 11,
  },
  {
    clientname: "Callida Adds",
    image: "http://dummyimage.com/118x100.png/dddddd/000000",
    quantity: 4,
    weight: 6.2,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "pendiente",
    userId: 13,
  },
  {
    clientname: "Cad Willimot",
    image: "http://dummyimage.com/186x100.png/cc0000/ffffff",
    quantity: 4,
    weight: 7.0,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 19,
  },
  {
    clientname: "Jenifer Ribchester",
    image: "http://dummyimage.com/192x100.png/5fa2dd/ffffff",
    quantity: 4,
    weight: 4.63,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 13,
  },
  {
    clientname: "Aloisia Brownfield",
    image: "http://dummyimage.com/116x100.png/ff4444/ffffff",
    quantity: 2,
    weight: 2.99,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 5,
  },
  {
    clientname: "Junina Ungerecht",
    image: "http://dummyimage.com/175x100.png/dddddd/000000",
    quantity: 3,
    weight: 9.51,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "pendiente",
    userId: 2,
  },
  {
    clientname: "Mira Trayte",
    image: "http://dummyimage.com/223x100.png/dddddd/000000",
    quantity: 4,
    weight: 4.93,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "entregado",
    userId: 16,
  },
  {
    clientname: "Ellerey Heyworth",
    image: "http://dummyimage.com/174x100.png/cc0000/ffffff",
    quantity: 4,
    weight: 4.21,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 11,
  },
  {
    clientname: "Erika Lummasana",
    image: "http://dummyimage.com/120x100.png/ff4444/ffffff",
    quantity: 2,
    weight: 8.79,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 15,
  },
  {
    clientname: "Jaclyn Bollans",
    image: "http://dummyimage.com/225x100.png/ff4444/ffffff",
    quantity: 3,
    weight: 6.58,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "entregado",
    userId: 2,
  },
  {
    clientname: "Giffie Joslin",
    image: "http://dummyimage.com/198x100.png/5fa2dd/ffffff",
    quantity: 2,
    weight: 3.39,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "en curso",
    userId: 18,
  },
  {
    clientname: "Nil Cooling",
    image: "http://dummyimage.com/104x100.png/dddddd/000000",
    quantity: 2,
    weight: 7.04,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "en curso",
    userId: 17,
  },
  {
    clientname: "Loise McLarty",
    image: "http://dummyimage.com/143x100.png/5fa2dd/ffffff",
    quantity: 1,
    weight: 4.45,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 19,
  },
  {
    clientname: "Sterne Knobell",
    image: "http://dummyimage.com/239x100.png/ff4444/ffffff",
    quantity: 5,
    weight: 9.94,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 6,
  },
  {
    clientname: "Kissie Signore",
    image: "http://dummyimage.com/148x100.png/dddddd/000000",
    quantity: 4,
    weight: 7.82,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "pendiente",
    userId: 3,
  },
  {
    clientname: "Darin Tuddall",
    image: "http://dummyimage.com/154x100.png/dddddd/000000",
    quantity: 5,
    weight: 1.81,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "en curso",
    userId: 6,
  },
  {
    clientname: "Hadria Autie",
    image: "http://dummyimage.com/192x100.png/5fa2dd/ffffff",
    quantity: 2,
    weight: 1.01,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "en curso",
    userId: 5,
  },
  {
    clientname: "Raimund Nelson",
    image: "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
    quantity: 4,
    weight: 7.16,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 12,
  },
  {
    clientname: "Ruprecht Turfitt",
    image: "http://dummyimage.com/122x100.png/5fa2dd/ffffff",
    quantity: 3,
    weight: 2.98,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 8,
  },
  {
    clientname: "Ali Earley",
    image: "http://dummyimage.com/120x100.png/dddddd/000000",
    quantity: 1,
    weight: 8.61,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "pendiente",
    userId: 2,
  },
  {
    clientname: "Christian Rookes",
    image: "http://dummyimage.com/249x100.png/ff4444/ffffff",
    quantity: 3,
    weight: 4.92,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "entregado",
    userId: 16,
  },
  {
    clientname: "Craig Loch",
    image: "http://dummyimage.com/216x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 2.33,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "entregado",
    userId: 18,
  },
  {
    clientname: "Arturo Perago",
    image: "http://dummyimage.com/221x100.png/dddddd/000000",
    quantity: 5,
    weight: 1.78,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 9,
  },
  {
    clientname: "Odille Van den Bosch",
    image: "http://dummyimage.com/107x100.png/cc0000/ffffff",
    quantity: 3,
    weight: 1.23,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 6,
  },
  {
    clientname: "Giovanni Jostan",
    image: "http://dummyimage.com/137x100.png/dddddd/000000",
    quantity: 1,
    weight: 1.73,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "pendiente",
    userId: 5,
  },
  {
    clientname: "Flynn Di Domenico",
    image: "http://dummyimage.com/236x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 9.61,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "en curso",
    userId: 19,
  },
  {
    clientname: "Alf Gemnett",
    image: "http://dummyimage.com/146x100.png/ff4444/ffffff",
    quantity: 2,
    weight: 1.13,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "pendiente",
    userId: 10,
  },
  {
    clientname: "Gay Johanning",
    image: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
    quantity: 2,
    weight: 1.44,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 19,
  },
  {
    clientname: "Garry Lile",
    image: "http://dummyimage.com/188x100.png/cc0000/ffffff",
    quantity: 3,
    weight: 2.37,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 1,
  },
  {
    clientname: "Hewie Harness",
    image: "http://dummyimage.com/214x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 1.36,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "pendiente",
    userId: 10,
  },
  {
    clientname: "Sumner Sharplin",
    image: "http://dummyimage.com/184x100.png/ff4444/ffffff",
    quantity: 5,
    weight: 2.71,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "en curso",
    userId: 2,
  },
  {
    clientname: "Wynne Tellwright",
    image: "http://dummyimage.com/107x100.png/ff4444/ffffff",
    quantity: 5,
    weight: 7.94,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "entregado",
    userId: 11,
  },
  {
    clientname: "Luelle Alsopp",
    image: "http://dummyimage.com/163x100.png/5fa2dd/ffffff",
    quantity: 2,
    weight: 4.51,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 5,
  },
  {
    clientname: "Consuela Semour",
    image: "http://dummyimage.com/195x100.png/dddddd/000000",
    quantity: 5,
    weight: 8.64,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 12,
  },
  {
    clientname: "Sibel Godsil",
    image: "http://dummyimage.com/125x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 2.73,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 5,
  },
  {
    clientname: "Hart Vayne",
    image: "http://dummyimage.com/211x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 5.89,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "entregado",
    userId: 13,
  },
  {
    clientname: "Terrill Greensmith",
    image: "http://dummyimage.com/181x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 4.81,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "pendiente",
    userId: 7,
  },
  {
    clientname: "Emelda Crump",
    image: "http://dummyimage.com/132x100.png/cc0000/ffffff",
    quantity: 2,
    weight: 3.32,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 6,
  },
  {
    clientname: "Ronalda Klishin",
    image: "http://dummyimage.com/221x100.png/cc0000/ffffff",
    quantity: 3,
    weight: 9.05,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 3,
  },
  {
    clientname: "Myrtle Mc Gaughey",
    image: "http://dummyimage.com/151x100.png/dddddd/000000",
    quantity: 2,
    weight: 5.66,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "pendiente",
    userId: 18,
  },
  {
    clientname: "Kevin Brockbank",
    image: "http://dummyimage.com/250x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 6.06,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "en curso",
    userId: 7,
  },
  {
    clientname: "Ingamar Coulthurst",
    image: "http://dummyimage.com/189x100.png/5fa2dd/ffffff",
    quantity: 4,
    weight: 1.97,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "en curso",
    userId: 13,
  },
  {
    clientname: "Bernice Kermannes",
    image: "http://dummyimage.com/162x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 4.81,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 3,
  },
  {
    clientname: "Tristan Pumphrey",
    image: "http://dummyimage.com/248x100.png/dddddd/000000",
    quantity: 2,
    weight: 3.37,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 4,
  },
  {
    clientname: "Glyn Staries",
    image: "http://dummyimage.com/197x100.png/cc0000/ffffff",
    quantity: 1,
    weight: 4.1,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "pendiente",
    userId: 7,
  },
  {
    clientname: "Lorri Boothby",
    image: "http://dummyimage.com/223x100.png/dddddd/000000",
    quantity: 4,
    weight: 4.79,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "en curso",
    userId: 6,
  },
  {
    clientname: "Hetti Constable",
    image: "http://dummyimage.com/181x100.png/cc0000/ffffff",
    quantity: 4,
    weight: 5.7,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "en curso",
    userId: 5,
  },
  {
    clientname: "Felice Verling",
    image: "http://dummyimage.com/145x100.png/ff4444/ffffff",
    quantity: 3,
    weight: 7.67,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "pendiente",
    userId: 4,
  },
  {
    clientname: "Maddi Craik",
    image: "http://dummyimage.com/171x100.png/dddddd/000000",
    quantity: 2,
    weight: 6.79,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 6,
  },
  {
    clientname: "Perla Labusquiere",
    image: "http://dummyimage.com/213x100.png/dddddd/000000",
    quantity: 5,
    weight: 4.17,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "entregado",
    userId: 12,
  },
  {
    clientname: "Zackariah Gherardesci",
    image: "http://dummyimage.com/166x100.png/5fa2dd/ffffff",
    quantity: 5,
    weight: 2.29,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "pendiente",
    userId: 3,
  },
  {
    clientname: "Theo Still",
    image: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    quantity: 3,
    weight: 6.25,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "pendiente",
    userId: 1,
  },
  {
    clientname: "Shaughn Agron",
    image: "http://dummyimage.com/185x100.png/5fa2dd/ffffff",
    quantity: 3,
    weight: 8.91,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 18,
  },
  {
    clientname: "Kat Steddall",
    image: "http://dummyimage.com/241x100.png/cc0000/ffffff",
    quantity: 2,
    weight: 8.96,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 2,
  },
  {
    clientname: "Vikki Gadsdon",
    image: "http://dummyimage.com/208x100.png/ff4444/ffffff",
    quantity: 3,
    weight: 3.9,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 5,
  },
  {
    clientname: "Coop Hugonneau",
    image: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    quantity: 4,
    weight: 9.41,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "en curso",
    userId: 10,
  },
  {
    clientname: "Tom Gahagan",
    image: "http://dummyimage.com/146x100.png/ff4444/ffffff",
    quantity: 4,
    weight: 9.28,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "entregado",
    userId: 5,
  },
  {
    clientname: "Uriel Shepherd",
    image: "http://dummyimage.com/210x100.png/dddddd/000000",
    quantity: 2,
    weight: 9.91,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "pendiente",
    userId: 20,
  },
  {
    clientname: "Nickie Gillingwater",
    image: "http://dummyimage.com/176x100.png/ff4444/ffffff",
    quantity: 4,
    weight: 3.49,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 2,
  },
  {
    clientname: "Ilyse Lockney",
    image: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
    quantity: 1,
    weight: 8.71,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "en curso",
    userId: 20,
  },
  {
    clientname: "Ivie Ellings",
    image: "http://dummyimage.com/150x100.png/dddddd/000000",
    quantity: 2,
    weight: 1.48,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "entregado",
    userId: 2,
  },
  {
    clientname: "Tate Mainstone",
    image: "http://dummyimage.com/229x100.png/cc0000/ffffff",
    quantity: 1,
    weight: 8.98,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "en curso",
    userId: 4,
  },
  {
    clientname: "Bernadette Gutowska",
    image: "http://dummyimage.com/146x100.png/5fa2dd/ffffff",
    quantity: 4,
    weight: 8.49,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 19,
  },
  {
    clientname: "Hans Crumbie",
    image: "http://dummyimage.com/168x100.png/5fa2dd/ffffff",
    quantity: 1,
    weight: 6.92,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 5,
  },
  {
    clientname: "Ferris Mathelon",
    image: "http://dummyimage.com/202x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 7.37,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 11,
  },
  {
    clientname: "Garwood Noddle",
    image: "http://dummyimage.com/198x100.png/dddddd/000000",
    quantity: 2,
    weight: 2.72,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "entregado",
    userId: 18,
  },
  {
    clientname: "Lil Showen",
    image: "http://dummyimage.com/158x100.png/ff4444/ffffff",
    quantity: 5,
    weight: 1.53,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "entregado",
    userId: 14,
  },
  {
    clientname: "Noach Scurrey",
    image: "http://dummyimage.com/170x100.png/dddddd/000000",
    quantity: 4,
    weight: 6.21,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 2,
  },
  {
    clientname: "Trumann Maro",
    image: "http://dummyimage.com/174x100.png/cc0000/ffffff",
    quantity: 3,
    weight: 9.1,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 14,
  },
  {
    clientname: "Morry Fromont",
    image: "http://dummyimage.com/155x100.png/dddddd/000000",
    quantity: 1,
    weight: 4.77,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "entregado",
    userId: 7,
  },
  {
    clientname: "Esta Windress",
    image: "http://dummyimage.com/175x100.png/dddddd/000000",
    quantity: 5,
    weight: 7.67,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "entregado",
    userId: 11,
  },
  {
    clientname: "Dino Kellegher",
    image: "http://dummyimage.com/172x100.png/dddddd/000000",
    quantity: 4,
    weight: 7.75,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "entregado",
    userId: 5,
  },
  {
    clientname: "Kaitlynn Jozwiak",
    image: "http://dummyimage.com/198x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 5.76,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "en curso",
    userId: 1,
  },
  {
    clientname: "Barbette Iacovazzi",
    image: "http://dummyimage.com/111x100.png/dddddd/000000",
    quantity: 2,
    weight: 3.69,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 11,
  },
  {
    clientname: "Leah Lante",
    image: "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
    quantity: 2,
    weight: 8.53,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 16,
  },
  {
    clientname: "Batholomew Sayward",
    image: "http://dummyimage.com/249x100.png/cc0000/ffffff",
    quantity: 1,
    weight: 1.58,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "en curso",
    userId: 8,
  },
  {
    clientname: "Cathie Sowte",
    image: "http://dummyimage.com/217x100.png/5fa2dd/ffffff",
    quantity: 2,
    weight: 2.98,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "entregado",
    userId: 2,
  },
  {
    clientname: "Jany Prichet",
    image: "http://dummyimage.com/208x100.png/dddddd/000000",
    quantity: 4,
    weight: 7.57,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "entregado",
    userId: 4,
  },
  {
    clientname: "Hagen Popple",
    image: "http://dummyimage.com/176x100.png/cc0000/ffffff",
    quantity: 5,
    weight: 7.85,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 19,
  },
  {
    clientname: "Jock Pykerman",
    image: "http://dummyimage.com/127x100.png/dddddd/000000",
    quantity: 1,
    weight: 7.71,
    street: "Chapultepec",
    number: 1422,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64800,
    status: "entregado",
    userId: 14,
  },
  {
    clientname: "Christophorus Agge",
    image: "http://dummyimage.com/102x100.png/dddddd/000000",
    quantity: 2,
    weight: 2.33,
    street: "Lincoln",
    number: 4954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64330,
    status: "pendiente",
    userId: 5,
  },
  {
    clientname: "Mitch Barkworth",
    image: "http://dummyimage.com/138x100.png/ff4444/ffffff",
    quantity: 1,
    weight: 8.19,
    street: "Miguel Alemán",
    number: 1530,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66634,
    status: "pendiente",
    userId: 3,
  },
  {
    clientname: "Ardyce Denley",
    image: "http://dummyimage.com/168x100.png/cc0000/ffffff",
    quantity: 3,
    weight: 8.2,
    street: "Francisco I Madero",
    number: 837,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 10,
  },
  {
    clientname: "Hana Grebert",
    image: "http://dummyimage.com/200x100.png/ff4444/ffffff",
    quantity: 3,
    weight: 6.08,
    street: "Colón",
    number: 1610,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "pendiente",
    userId: 10,
  },
  {
    clientname: "Noach Weale",
    image: "http://dummyimage.com/201x100.png/ff4444/ffffff",
    quantity: 4,
    weight: 5.74,
    street: "José Benítez",
    number: 2307,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 3,
  },
  {
    clientname: "Linnie Robinette",
    image: "http://dummyimage.com/172x100.png/cc0000/ffffff",
    quantity: 1,
    weight: 9.99,
    street: "Padre Mier",
    number: 954,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64720,
    status: "pendiente",
    userId: 10,
  },
  {
    clientname: "Jeddy Osmon",
    image: "http://dummyimage.com/134x100.png/ff4444/ffffff",
    quantity: 4,
    weight: 2.57,
    street: "Dublin",
    number: 1003,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 66430,
    status: "pendiente",
    userId: 17,
  },
  {
    clientname: "Cordy McKern",
    image: "http://dummyimage.com/164x100.png/ff4444/ffffff",
    quantity: 2,
    weight: 6.94,
    street: "Degollado",
    number: 630,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64060,
    status: "en curso",
    userId: 8,
  },
  {
    clientname: "Gabrielle Milson",
    image: "http://dummyimage.com/191x100.png/ff4444/ffffff",
    quantity: 2,
    weight: 9.69,
    street: "Washington",
    number: 118,
    city: "Monterrey",
    province: "Nuevo León",
    postalCode: 64000,
    status: "entregado",
    userId: 6,
  },
];

for (let i = 0; i < packageData.length; i++) {
  const dia = Math.ceil(Math.random() * 30);
  const mes = Math.floor(Math.random() * 3) + 6;
  packageData[i].deliveryday = new Date(2023, mes, dia);
}

const packages: IPackage[] = packageData;

export default async function createAllPackages() {
  for (let i = 0; i < packages.length; i++) {
    const pack = packages[i];
    await Package.create(pack);
  }
  console.log("packages create ok");
}

export { createAllPackages };
